import = ["~/.config/sesh/configs/nu-sesh.toml"]

[default_session]
startup_command = "nvim +GoToFile"

# TODO: potential feature ideas
# [[session]]
# name = "session"
# path = "~/path/to/session"
# startup_script = "~/git_repos/dotfiles/sesh/bin/spotify.sh"
# detached = true # never attach to this session, just create it in the background
# tmuxp = "~/.config/tmux/tmuxp/joshmedeski.com.yml"
# tmuxinator = "~/.config/tmux/tmuxinator/joshmedeski.com.yml"
#

[[session]]
startup_command = 'OLLAMA_ORIGINS="app://obsidian.md*" ollama serve'

name = "ollama"
path = "~"
[[session]]
name = "macmon"
path = "~/"
startup_command = "macmon"

[[session]]
name = "update"
path = "/tmp"
startup_command = "update"

[[session]]
name = "aerospace config"
path = "~/c/dotfiles/.config/aerospace"
startup_command = "nvim aerospace.toml"

[[session]]
name = "ghostty config"
path = "~/c/dotfiles/.config/ghostty"
startup_command = "nvim config"

[[session]]
name = "nutiliti worktrees"
path = "~/c/nu"
startup_command = "nu-worktree-picker.sh"

[[session]]
name = "nutiliti reviews"
path = "~/c/nu/review"
startup_command = "gh dash"

[[session]]
name = "Home 🏡"
path = "~"
startup_command = "l"

[[session]]
name = "Code 💻"
path = "~/c"
startup_command = "l"

[[session]]
name = "tmux config"
path = "~/c/dotfiles/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "gitmux config"
path = "~/c/dotfiles/.config/tmux"
startup_command = "nvim gitmux.conf"

[[session]]
name = "hammerspoon config"
path = "~/c/dotfiles/.hammerspoon"

[[session]]
name = "neovim config"
path = "~/c/dotfiles/.config/nvim"

[[session]]
name = "fish config"
path = "~/c/dotfiles/.config/fish"
startup_command = "nvim config.fish"

[[session]]
name = "yazi config"
path = "~/c/dotfiles/.config/yazi"
startup_command = "nvim yazi.toml"

[[session]]
name = "wezterm config"
path = "~/c/dotfiles/.config/wezterm"
startup_command = "nvim wezterm.lua"

[[session]]
name = "nutiliti new worktree"
path = "~/c/nu"
# TODO: auto-close this session when the worktree has been created successfully?  
# TODO: append [[session]] ./nu/{name}/package/* to this config for dev mode bonus
startup_commad = "nu_new_worktree"

[[session]]
name = "second brain 🧠"
path = "~/c/second-brain"
startup_command = "nvim +ObsidianToday"

[[session]]
name = "sesh config"
path = "~/c/dotfiles/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "my custom binaries"
path = "~/c/dotfiles/.config/bin"

[[session]]
name = "dotfiles"
path = "~/c/dotfiles"
# startup_command = "u"

[[session]]
name = "blog posts"
path = "~/c/joshmedeski.com/src/content/posts"

[[session]]
path = "~/c/joshmedeski.com"
startup_script = "~/.config/sesh/scripts/node_dev"

[[session]]
session_path = "~/c/nu/main/packages/*"
script_path = "~/.config/sesh/scripts/node_dev"


# TODO: implement this 
# script_command = "nvim ~/.tmux"

[[session]]
name = "tmux-fzf-url 🖇️"
path = "~/.config/tmux/plugins/tmux-fzf-url"
startup_command = "nvim fzf-url.sh"

[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "lazy plugins"
path = "~/.local/share/nvim/lazy"
startup_command = "sesh connect (ls | fzf --ansi --no-border --preview 'glow -s light {}/README.md' --preview-window=right:85,border-none) && exit"

[[session]]
name = "karabiner elements"
path = "~/c/dotfiles/.config/karabiner"

[[session]]
name = "perplexica"
path = "~/c/perplexica"
startup_command = "docker compose up -d"

[[session]]
name = "/ect/hosts"
path = "/etc"
startup_command = "sudo nvim hosts"

[[session]]
name = "ssh"
path = "~/.config/ssh"
startup_command = "sudo nvim config"

[[session]]
name = "steam deck"
path = "~/.ssh"
startup_command = "ssh deck@steamdeck"
