default_startup_script = "~/.config/sesh/scripts/open_files"

[[startup_scripts]]
session_path = "~/c/joshmedeski.com"
script_path = "~/.config/sesh/scripts/node_dev"

[[startup_scripts]]
session_path = "~/c/nu/*"
script_path = "~/.config/sesh/scripts/nu_dev"
